### ISSUE TITLE
Coordinated releases to makehuman

### ISSUE THREAD

**Issue by evlli** [makehumancommunity/makehuman-assets#5]
makehuman v1.3.0 is released, yet no tag for makehuman-assets with that version was made.

is this desired?

I would like to know so I can update in nixpkgs

**Comment by joepal1976** [comment]
Since no changes have been made in this repo for a few years, we haven't really bothered keeping up with tags.

But if a new tag is needed, I see no problem with having one. I've pushed v1.3.0 now.

https://github.com/makehumancommunity/makehuman-assets/tree/v1.3.0

**Comment by evlli** [comment]
lovely, thanks :heart:
